import {
  StateGraph,
  StateSchema,
  START,
  END,
  type GraphNode,
} from "@langchain/langgraph";

import { z } from "zod";
import { cohere, gemini, mistral } from "./ai.langchain.js";
import { createAgent, HumanMessage, providerStrategy } from "langchain";

const State = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_reasoning: z.string().default(""),
    solution_2_reasoning: z.string().default(""),
  }),
});

// solution node
export const solutionNode: GraphNode<typeof State> = async (state) => {
  const [MistralResponse, CohereResponse] = await Promise.all([
    mistral.invoke(state.problem),
    cohere.invoke(state.problem),
  ]);
  return {
    solution_1: MistralResponse.text,
    solution_2: CohereResponse.text,
  };
};

// judge node
export const judgeNode: GraphNode<typeof State> = async (state) => {
  const { problem, solution_1, solution_2 } = state;
  const judge = createAgent({
    model: gemini,
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
      }),
    ),
    systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores. `,
  });

  const judgeResponse = await judge.invoke({
    messages: [
      new HumanMessage(
        `Problem: ${problem}
        Solution 1: ${solution_1}
        Solution 2: ${solution_2}
        Please evaluate the two solutions and provide scores and reasoning.`,
      ),
    ],
  });

  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
  } = judgeResponse.structuredResponse;

  return {
    judge: {
      solution_1_score,
      solution_2_score,
      solution_1_reasoning,
      solution_2_reasoning,
    },
  };
};

// graph

const graph = new StateGraph(State)
  .addNode("solution", solutionNode)
  .addNode("judge-node", judgeNode)
  .addEdge(START, "solution")
  .addEdge("solution", "judge-node")
  .addEdge("judge-node", END)
  .compile();

export default async function (problem: string) {
  const result = await graph.invoke({
    problem: problem,
  });
  return result;
}
